import "./globals.css";

import type { Metadata } from "next";
import { Josefin_Sans, Noto_Sans_JP } from "next/font/google";

import { GradationBackground } from "@/components/GradationBackground";
import { LoadingScreen } from "@/components/LoadingScreen";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  display: "swap",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${josefinSans.variable} ${notoSansJP.variable}`}>
        <LoadingScreen />
        <GradationBackground />

        <main>{children}</main>
      </body>
    </html>
  );
}
